export const BrowserRoute = {
  notFound: "*",
  startPage: "/",
  SCHEDULE_PAGE: "/schedule",
  ADMIN: "/admin",
  ADMIN_SCHEDULE: "schedule",
  ADMIN_TEACHER: "teacher",
  ADMIN_TEACHER_LIST: "list",
  ADMIN_TEACHER_CREATE: "create",
  ADMIN_SUBJECT: "subject",
  ADMIN_CLASSROOM: "classroom",
  ADMIN_GROUP: "group",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
};
