const None = null;

export const schedule1 = [{'courses': [{'course': 1,
    'subjects': [{'classroom': 'B202',
      'code': 'MDE119',
      'numberOfHours': 1,
      'teachers': 'Niko Robin',
      'title': 'Ecology'},
      {'classroom': 'B202',
        'code': 'COM109',
        'numberOfHours': 1,
        'teachers': 'Alex Blare',
        'title': 'English language'},
      {'classroom': 'B204',
        'code': 'COM107',
        'numberOfHours': 1,
        'teachers': 'Zoro Roronoa',
        'title': 'Physics 1'},
      {'classroom': 'B202',
        'code': 'COM105',
        'numberOfHours': 1,
        'teachers': 'Zoro Roronoa',
        'title': 'Calculus1'},
      {'classroom': 'B202',
        'code': 'COM109',
        'numberOfHours': 1,
        'teachers': 'Alex Blare',
        'title': 'English language'},
      None,
      None,
      {'classroom': 'B204',
        'code': 'MDE119',
        'numberOfHours': 1,
        'teachers': 'Niko Robin',
        'title': 'Ecology'},
      {'classroom': 'B204',
        'code': 'COM105',
        'numberOfHours': 1,
        'teachers': 'Zoro Roronoa',
        'title': 'Calculus1'},
      {'classroom': 'B204',
        'code': 'COM103',
        'numberOfHours': 1,
        'teachers': 'Zoro Roronoa',
        'title': 'Programming Language 1'},
      {'classroom': 'B203',
        'code': 'COM107',
        'numberOfHours': 1,
        'teachers': 'Zoro Roronoa',
        'title': 'Physics 1'}]},
    {'course': 2,
      'subjects': [None,
        {'classroom': 'B202',
          'code': 'COM209',
          'numberOfHours': 1,
          'teachers': 'Franky Cyborg',
          'title': 'Electrotechnics&Electronics'},
        None,
        None,
        None,
        None,
        {'classroom': 'B202',
          'code': 'MDE227',
          'numberOfHours': 1,
          'teachers': 'Franky Cyborg',
          'title': 'Physical Education 3'},
        None,
        {'classroom': 'B202',
          'code': 'MDE227',
          'numberOfHours': 1,
          'teachers': 'Franky Cyborg',
          'title': 'Physical Education 3'},
        {'classroom': 'B202',
          'code': 'COM209',
          'numberOfHours': 1,
          'teachers': 'Franky Cyborg',
          'title': 'Electrotechnics&Electronics'},
        {'classroom': 'B205',
          'code': 'COM203',
          'numberOfHours': 1,
          'teachers': 'Sanji Vinsmoke',
          'title': 'Web Technologies'}]},
    {'course': 3,
      'subjects': [{'classroom': 'B203',
        'code': 'COM309',
        'numberOfHours': 1,
        'teachers': 'Zoro Roronoa',
        'title': 'Probability and Statistics'},
        {'classroom': 'B204',
          'code': 'COM301',
          'numberOfHours': 1,
          'teachers': 'Dim Shayakhmetov',
          'title': 'Design & Analysis of Algorithms'},
        {'classroom': 'B205',
          'code': 'COM305',
          'numberOfHours': 1,
          'teachers': 'Ruslan Isaev',
          'title': 'Software Engineering 1'},
        None,
        {'classroom': 'B201',
          'code': 'COM301',
          'numberOfHours': 1,
          'teachers': 'Dim Shayakhmetov',
          'title': 'Design & Analysis of Algorithms'},
        None,
        {'classroom': 'B205',
          'code': 'COM307',
          'numberOfHours': 1,
          'teachers': 'Imtiyaz Gulbarga',
          'title': 'Computer Networks and Telecommunication'},
        None,
        None,
        None,
        {'classroom': 'B204',
          'code': 'COM303',
          'numberOfHours': 1,
          'teachers': 'Nurmuhammed Abdullaev',
          'title': 'Mobile App Development'}]},
    {'course': 4,
      'subjects': [{'classroom': 'B202',
        'code': 'COM431',
        'numberOfHours': 1,
        'teachers': 'Ruslan Isaev',
        'title': 'Image Processing'},
        {'classroom': 'B202',
          'code': 'COM402',
          'numberOfHours': 1,
          'teachers': 'Usopp Sniper',
          'title': 'Academic research'},
        {'classroom': 'B201',
          'code': 'COM401',
          'numberOfHours': 1,
          'teachers': 'Imtiyaz Gulbarga',
          'title': 'Information Security'},
        None,
        {'classroom': 'B205',
          'code': 'COM409',
          'numberOfHours': 1,
          'teachers': 'Burul Shambetov',
          'title': 'Human Computer Interaction'},
        None,
        None,
        {'classroom': 'B204',
          'code': 'COM441',
          'numberOfHours': 1,
          'teachers': 'Sanji Vinsmoke',
          'title': 'Design & Software architecture'},
        {'classroom': 'B201',
          'code': 'COM421',
          'numberOfHours': 1,
          'teachers': 'Burul Shambetov',
          'title': 'Industrial Internship'},
        {'classroom': 'B203',
          'code': 'COM441',
          'numberOfHours': 1,
          'teachers': 'Sanji Vinsmoke',
          'title': 'Design & Software architecture'},
        {'classroom': 'B203',
          'code': 'COM421',
          'numberOfHours': 1,
          'teachers': 'Burul Shambetov',
          'title': 'Industrial Internship'}]}],
  'day': 'Monday'},
  {'courses': [{'course': 1,
      'subjects': [{'classroom': 'B201',
        'code': 'COM111',
        'numberOfHours': 1,
        'teachers': 'Alex Blare',
        'title': 'Turkish language'},
        {'classroom': 'B202',
          'code': 'COM107',
          'numberOfHours': 1,
          'teachers': 'Zoro Roronoa',
          'title': 'Physics 1'},
        {'classroom': 'B205',
          'code': 'MDE119',
          'numberOfHours': 1,
          'teachers': 'Niko Robin',
          'title': 'Ecology'},
        {'classroom': 'B201',
          'code': 'COM109',
          'numberOfHours': 1,
          'teachers': 'Alex Blare',
          'title': 'English language'},
        {'classroom': 'B201',
          'code': 'COM111',
          'numberOfHours': 1,
          'teachers': 'Alex Blare',
          'title': 'Turkish language'},
        None,
        {'classroom': 'B202',
          'code': 'COM105',
          'numberOfHours': 1,
          'teachers': 'Zoro Roronoa',
          'title': 'Calculus1'},
        {'classroom': 'B201',
          'code': 'COM103',
          'numberOfHours': 1,
          'teachers': 'Zoro Roronoa',
          'title': 'Programming Language 1'},
        None,
        None,
        None]},
      {'course': 2,
        'subjects': [None,
          None,
          None,
          {'classroom': 'B202',
            'code': 'COM209',
            'numberOfHours': 1,
            'teachers': 'Franky Cyborg',
            'title': 'Electrotechnics&Electronics'},
          {'classroom': 'B202',
            'code': 'MDE201',
            'numberOfHours': 1,
            'teachers': 'Niko Robin',
            'title': 'Kyrgyz Language and Literature'},
          None,
          None,
          None,
          {'classroom': 'B202',
            'code': 'COM209',
            'numberOfHours': 1,
            'teachers': 'Franky Cyborg',
            'title': 'Electrotechnics&Electronics'},
          None,
          {'classroom': 'B202',
            'code': 'COM207',
            'numberOfHours': 1,
            'teachers': 'Zoro Roronoa',
            'title': 'Discrete Mathematics'}]},
      {'course': 3,
        'subjects': [{'classroom': 'B205',
          'code': 'COM307',
          'numberOfHours': 1,
          'teachers': 'Imtiyaz Gulbarga',
          'title': 'Computer Networks and Telecommunication'},
          None,
          None,
          None,
          {'classroom': 'B205',
            'code': 'COM303',
            'numberOfHours': 1,
            'teachers': 'Nurmuhammed Abdullaev',
            'title': 'Mobile App Development'},
          None,
          None,
          None,
          {'classroom': 'B201',
            'code': 'COM307',
            'numberOfHours': 1,
            'teachers': 'Imtiyaz Gulbarga',
            'title': 'Computer Networks and Telecommunication'},
          None,
          None]},
      {'course': 4,
        'subjects': [None,
          {'classroom': 'B205',
            'code': 'COM440',
            'numberOfHours': 1,
            'teachers': 'Jimbei Warrior',
            'title': 'Data-Mining'},
          None,
          {'classroom': 'B203',
            'code': 'COM431',
            'numberOfHours': 1,
            'teachers': 'Ruslan Isaev',
            'title': 'Image Processing'},
          {'classroom': 'B205',
            'code': 'COM441',
            'numberOfHours': 1,
            'teachers': 'Sanji Vinsmoke',
            'title': 'Design & Software architecture'},
          None,
          {'classroom': 'B201',
            'code': 'COM421',
            'numberOfHours': 1,
            'teachers': 'Burul Shambetov',
            'title': 'Industrial Internship'},
          None,
          None,
          {'classroom': 'B205',
            'code': 'COM409',
            'numberOfHours': 1,
            'teachers': 'Burul Shambetov',
            'title': 'Human Computer Interaction'},
          None]}],
    'day': 'Tuesday'},
  {'courses': [{'course': 1,
      'subjects': [{'classroom': 'B201',
        'code': 'COM105',
        'numberOfHours': 1,
        'teachers': 'Zoro Roronoa',
        'title': 'Calculus1'},
        {'classroom': 'B205',
          'code': 'MDE105',
          'numberOfHours': 1,
          'teachers': 'Nami Cat',
          'title': 'Russian language 1'},
        {'classroom': 'B204',
          'code': 'COM101',
          'numberOfHours': 1,
          'teachers': 'Dastan Bayizbekov',
          'title': 'Introduction to Engineering and Computer Science'},
        {'classroom': 'B202',
          'code': 'COM101',
          'numberOfHours': 1,
          'teachers': 'Dastan Bayizbekov',
          'title': 'Introduction to Engineering and Computer Science'},
        None,
        None,
        None,
        None,
        {'classroom': 'B201',
          'code': 'COM103',
          'numberOfHours': 1,
          'teachers': 'Zoro Roronoa',
          'title': 'Programming Language 1'},
        None,
        {'classroom': 'B202',
          'code': 'COM107',
          'numberOfHours': 1,
          'teachers': 'Zoro Roronoa',
          'title': 'Physics 1'}]},
      {'course': 2,
        'subjects': [{'classroom': 'B202',
          'code': 'COM203',
          'numberOfHours': 1,
          'teachers': 'Sanji Vinsmoke',
          'title': 'Web Technologies'},
          None,
          None,
          {'classroom': 'B202',
            'code': 'COM201',
            'numberOfHours': 1,
            'teachers': 'Sanji Vinsmoke',
            'title': 'Object Oriented Programming (OOP)'},
          None,
          None,
          {'classroom': 'B202',
            'code': 'COM209',
            'numberOfHours': 1,
            'teachers': 'Franky Cyborg',
            'title': 'Electrotechnics&Electronics'},
          {'classroom': 'B202',
            'code': 'COM207',
            'numberOfHours': 1,
            'teachers': 'Zoro Roronoa',
            'title': 'Discrete Mathematics'},
          {'classroom': 'B204',
            'code': 'COM209',
            'numberOfHours': 1,
            'teachers': 'Franky Cyborg',
            'title': 'Electrotechnics&Electronics'},
          None,
          None]},
      {'course': 3,
        'subjects': [{'classroom': 'B205',
          'code': 'COM305',
          'numberOfHours': 1,
          'teachers': 'Ruslan Isaev',
          'title': 'Software Engineering 1'},
          {'classroom': 'B201',
            'code': 'COM311',
            'numberOfHours': 1,
            'teachers': 'Ban Black',
            'title': 'Introduction to Enterpreunership'},
          {'classroom': 'B203',
            'code': 'COM311',
            'numberOfHours': 1,
            'teachers': 'Ban Black',
            'title': 'Introduction to Enterpreunership'},
          {'classroom': 'B205',
            'code': 'COM303',
            'numberOfHours': 1,
            'teachers': 'Nurmuhammed Abdullaev',
            'title': 'Mobile App Development'},
          {'classroom': 'B202',
            'code': 'COM307',
            'numberOfHours': 1,
            'teachers': 'Imtiyaz Gulbarga',
            'title': 'Computer Networks and Telecommunication'},
          None,
          {'classroom': 'B202',
            'code': 'COM303',
            'numberOfHours': 1,
            'teachers': 'Nurmuhammed Abdullaev',
            'title': 'Mobile App Development'},
          {'classroom': 'B204',
            'code': 'COM313',
            'numberOfHours': 1,
            'teachers': 'Burul Shambetov',
            'title': 'Pedagogical Internship'},
          None,
          {'classroom': 'B202',
            'code': 'COM303',
            'numberOfHours': 1,
            'teachers': 'Nurmuhammed Abdullaev',
            'title': 'Mobile App Development'},
          None]},
      {'course': 4,
        'subjects': [{'classroom': 'B205',
          'code': 'COM443',
          'numberOfHours': 1,
          'teachers': 'Ruslan Isaev',
          'title': 'Robotics'},
          {'classroom': 'B203',
            'code': 'COM441',
            'numberOfHours': 1,
            'teachers': 'Sanji Vinsmoke',
            'title': 'Design & Software architecture'},
          {'classroom': 'B202',
            'code': 'COM443',
            'numberOfHours': 1,
            'teachers': 'Ruslan Isaev',
            'title': 'Robotics'},
          {'classroom': 'B203',
            'code': 'COM409',
            'numberOfHours': 1,
            'teachers': 'Burul Shambetov',
            'title': 'Human Computer Interaction'},
          {'classroom': 'B201',
            'code': 'COM402',
            'numberOfHours': 1,
            'teachers': 'Usopp Sniper',
            'title': 'Academic research'},
          None,
          None,
          {'classroom': 'B201',
            'code': 'COM441',
            'numberOfHours': 1,
            'teachers': 'Sanji Vinsmoke',
            'title': 'Design & Software architecture'},
          None,
          None,
          None]}],
    'day': 'Wednesday'},
  {'courses': [{'course': 1,
      'subjects': [None,
        {'classroom': 'B204',
          'code': 'COM101',
          'numberOfHours': 1,
          'teachers': 'Dastan Bayizbekov',
          'title': 'Introduction to Engineering and Computer Science'},
        None,
        {'classroom': 'B205',
          'code': 'COM109',
          'numberOfHours': 1,
          'teachers': 'Alex Blare',
          'title': 'English language'},
        {'classroom': 'B203',
          'code': 'COM101',
          'numberOfHours': 1,
          'teachers': 'Dastan Bayizbekov',
          'title': 'Introduction to Engineering and Computer Science'},
        None,
        None,
        None,
        None,
        None,
        {'classroom': 'B201',
          'code': 'COM103',
          'numberOfHours': 1,
          'teachers': 'Zoro Roronoa',
          'title': 'Programming Language 1'}]},
      {'course': 2,
        'subjects': [None,
          None,
          None,
          None,
          None,
          None,
          None,
          None,
          None,
          None,
          {'classroom': 'B202',
            'code': 'COM203',
            'numberOfHours': 1,
            'teachers': 'Sanji Vinsmoke',
            'title': 'Web Technologies'}]},
      {'course': 3,
        'subjects': [{'classroom': 'B203',
          'code': 'COM307',
          'numberOfHours': 1,
          'teachers': 'Imtiyaz Gulbarga',
          'title': 'Computer Networks and Telecommunication'},
          {'classroom': 'B202',
            'code': 'COM301',
            'numberOfHours': 1,
            'teachers': 'Dim Shayakhmetov',
            'title': 'Design & Analysis of Algorithms'},
          {'classroom': 'B203',
            'code': 'COM301',
            'numberOfHours': 1,
            'teachers': 'Dim Shayakhmetov',
            'title': 'Design & Analysis of Algorithms'},
          None,
          {'classroom': 'B201',
            'code': 'COM305',
            'numberOfHours': 1,
            'teachers': 'Ruslan Isaev',
            'title': 'Software Engineering 1'},
          None,
          {'classroom': 'B205',
            'code': 'COM309',
            'numberOfHours': 1,
            'teachers': 'Zoro Roronoa',
            'title': 'Probability and Statistics'},
          None,
          {'classroom': 'B203',
            'code': 'COM303',
            'numberOfHours': 1,
            'teachers': 'Nurmuhammed Abdullaev',
            'title': 'Mobile App Development'},
          {'classroom': 'B205',
            'code': 'COM309',
            'numberOfHours': 1,
            'teachers': 'Zoro Roronoa',
            'title': 'Probability and Statistics'},
          None]},
      {'course': 4,
        'subjects': [None,
          {'classroom': 'B201',
            'code': 'COM421',
            'numberOfHours': 1,
            'teachers': 'Burul Shambetov',
            'title': 'Industrial Internship'},
          {'classroom': 'B204',
            'code': 'COM440',
            'numberOfHours': 1,
            'teachers': 'Jimbei Warrior',
            'title': 'Data-Mining'},
          {'classroom': 'B205',
            'code': 'COM427',
            'numberOfHours': 1,
            'teachers': 'Ruslan Isaev',
            'title': 'Front-end Development'},
          None,
          None,
          {'classroom': 'B205',
            'code': 'COM402',
            'numberOfHours': 1,
            'teachers': 'Usopp Sniper',
            'title': 'Academic research'},
          None,
          None,
          {'classroom': 'B202',
            'code': 'COM401',
            'numberOfHours': 1,
            'teachers': 'Imtiyaz Gulbarga',
            'title': 'Information Security'},
          {'classroom': 'B205',
            'code': 'COM440',
            'numberOfHours': 1,
            'teachers': 'Jimbei Warrior',
            'title': 'Data-Mining'}]}],
    'day': 'Thursday'},
  {'courses': [{'course': 1,
      'subjects': [None,
        {'classroom': 'B205',
          'code': 'COM103',
          'numberOfHours': 1,
          'teachers': 'Zoro Roronoa',
          'title': 'Programming Language 1'},
        {'classroom': 'B202',
          'code': 'COM105',
          'numberOfHours': 1,
          'teachers': 'Zoro Roronoa',
          'title': 'Calculus1'},
        {'classroom': 'B201',
          'code': 'COM105',
          'numberOfHours': 1,
          'teachers': 'Zoro Roronoa',
          'title': 'Calculus1'},
        None,
        None,
        {'classroom': 'B205',
          'code': 'MDE131',
          'numberOfHours': 1,
          'teachers': 'Franky Cyborg',
          'title': 'Physical training 1'},
        {'classroom': 'B201',
          'code': 'MDE105',
          'numberOfHours': 1,
          'teachers': 'Nami Cat',
          'title': 'Russian language 1'},
        {'classroom': 'B205',
          'code': 'MDE105',
          'numberOfHours': 1,
          'teachers': 'Nami Cat',
          'title': 'Russian language 1'},
        None,
        None]},
      {'course': 2,
        'subjects': [None,
          None,
          {'classroom': 'B204',
            'code': 'MDE201',
            'numberOfHours': 1,
            'teachers': 'Niko Robin',
            'title': 'Kyrgyz Language and Literature'},
          None,
          {'classroom': 'B202',
            'code': 'COM207',
            'numberOfHours': 1,
            'teachers': 'Zoro Roronoa',
            'title': 'Discrete Mathematics'},
          None,
          None,
          None,
          {'classroom': 'B202',
            'code': 'MDE201',
            'numberOfHours': 1,
            'teachers': 'Niko Robin',
            'title': 'Kyrgyz Language and Literature'},
          None,
          None]},
      {'course': 3,
        'subjects': [{'classroom': 'B203',
          'code': 'COM301',
          'numberOfHours': 1,
          'teachers': 'Dim Shayakhmetov',
          'title': 'Design & Analysis of Algorithms'},
          {'classroom': 'B204',
            'code': 'COM309',
            'numberOfHours': 1,
            'teachers': 'Zoro Roronoa',
            'title': 'Probability and Statistics'},
          {'classroom': 'B205',
            'code': 'COM301',
            'numberOfHours': 1,
            'teachers': 'Dim Shayakhmetov',
            'title': 'Design & Analysis of Algorithms'},
          {'classroom': 'B205',
            'code': 'COM303',
            'numberOfHours': 1,
            'teachers': 'Nurmuhammed Abdullaev',
            'title': 'Mobile App Development'},
          {'classroom': 'B203',
            'code': 'COM305',
            'numberOfHours': 1,
            'teachers': 'Ruslan Isaev',
            'title': 'Software Engineering 1'},
          None,
          None,
          None,
          {'classroom': 'B205',
            'code': 'COM303',
            'numberOfHours': 1,
            'teachers': 'Nurmuhammed Abdullaev',
            'title': 'Mobile App Development'},
          None,
          None]},
      {'course': 4,
        'subjects': [{'classroom': 'B202',
          'code': 'COM427',
          'numberOfHours': 1,
          'teachers': 'Ruslan Isaev',
          'title': 'Front-end Development'},
          {'classroom': 'B202',
            'code': 'COM443',
            'numberOfHours': 1,
            'teachers': 'Ruslan Isaev',
            'title': 'Robotics'},
          {'classroom': 'B202',
            'code': 'COM401',
            'numberOfHours': 1,
            'teachers': 'Imtiyaz Gulbarga',
            'title': 'Information Security'},
          {'classroom': 'B201',
            'code': 'COM441',
            'numberOfHours': 1,
            'teachers': 'Sanji Vinsmoke',
            'title': 'Design & Software architecture'},
          {'classroom': 'B205',
            'code': 'COM431',
            'numberOfHours': 1,
            'teachers': 'Ruslan Isaev',
            'title': 'Image Processing'},
          None,
          {'classroom': 'B204',
            'code': 'COM402',
            'numberOfHours': 1,
            'teachers': 'Usopp Sniper',
            'title': 'Academic research'},
          None,
          None,
          {'classroom': 'B203',
            'code': 'COM402',
            'numberOfHours': 1,
            'teachers': 'Usopp Sniper',
            'title': 'Academic research'},
          {'classroom': 'B202',
            'code': 'COM401',
            'numberOfHours': 1,
            'teachers': 'Imtiyaz Gulbarga',
            'title': 'Information Security'}]}],
    'day': 'Friday'}]
